Repository 0xAlphaDevs/Near-Bitcoin-Agent, pull requests merged in 2025-04, with the labels that each got.

#13 Fixes #4 : Add tool to get BTC balance
  src/app/api/ai-plugin/route.ts
  src/app/api/tools/get-btc-balance/route.ts
Labels: feature

#17 Created Code of Conduct, PR Template, and Issue Template
  code_of_conduct.md
  issue_template.md
  pull_request_template.md
Labels: documentation

#18 Fixes #16 : Updated landing page
  public/x.png
  src/app/page.tsx
  src/components/ui/badge.tsx
Labels: enhancement

#29 Update agent link
  src/app/page.tsx
Labels: enhancement

#31 Fix : change mb-metadata header to searchParams
  package.json
  pnpm-lock.yaml
  src/app/api/ai-plugin/route.ts
  src/app/api/tools/create-btc-mpc-txn/route.ts
  src/app/api/tools/get-btc-balance/route.ts
  src/app/api/tools/get-user/route.ts
  src/app/api/tools/send-btc-txn/route.ts
  src/app/config.ts
Labels: enhancement

#32 Fix variable namings
  src/app/api/ai-plugin/route.ts
  src/app/api/tools/get-btc-balance/route.ts
  src/app/api/tools/get-user/route.ts
Labels: enhancement

#34 Fixes #33 Metadata not rendering properly
  src/app/layout.tsx
  src/app/page.tsx
Labels: bug

#36 Fixes #35 remove metadata from page.tsx
  src/app/page.tsx
Labels: bug

#46 Fixes #43 : Create dashboard page
  src/app/dashboard/page.tsx
Labels: feature

#48 Fixes #47 : Create Dashboard UI
  package.json
  pnpm-lock.yaml
  src/app/dashboard/page.tsx
  src/app/page.tsx
  src/components/ui/tabs.tsx
Labels: enhancement
