Repository 0xAlphaDevs/Near-Bitcoin-Agent, pull requests merged in 2025-08, with the labels that each got.

#113 Fixes#112 : Aligned Project Timeline on Landing Page
  src/app/page.tsx
Labels: enhancement

#118 Fixes #114 : Update ai-plugin
  src/app/api/ai-plugin/route.ts
Labels: enhancement

#122 Fixes #116 : Add path for get-near-intents-deposit in ai-plugin
  src/app/api/ai-plugin/route.ts
Labels: enhancement, feature

#131 Fixes #127 : Added mock implementation for check-supported-token
  src/app/api/ai-plugin/route.ts
Labels: enhancement

#143 Fixes #142 : update api call for check-supported-token-tool
  src/app/api/ai-plugin/route.ts
Labels: enhancement, feature

#145 Fixes #144 : Update agent instructions to swap NEAR Intents supported tokens to BTC
  src/app/api/ai-plugin/route.ts
Labels: enhancement

#157 Fixes #156: Added expanded competitive analysis to docs
  docs/expanded-competitive-analysis.md
  docs/technical-roadmap.md
Labels: documentation

#161 Fixes #160: Add Bitte Widget Component to Dashboard
  package.json
  pnpm-lock.yaml
  src/app/api/chat/route.ts
  src/app/api/history/route.ts
  src/app/dashboard/page.tsx
  src/components/ChatWidget.tsx
Labels: feature

#164 Fixes #162: Fix Bitte Widget UI Interference on Dashboard
  src/app/dashboard/page.tsx
  src/app/widget-iframe/page.tsx
Labels: bug

#167 Fixes #166 : Fix wallet context issue in widget
  src/app/widget-iframe/layout.tsx
  src/app/widget-iframe/page.tsx
Labels: bug

#169 Fixes #168: Update widget trigger UI and agent details
  public/icon.svg
  src/app/dashboard/page.tsx
  src/app/widget-iframe/page.tsx
Labels: enhancement

#171 Fixes #170: Fix Next.js hydration issues in dashboard and widget
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/widget-iframe/page.tsx
Labels: bug
