Repository 0xAlphaDevs/Near-Bitcoin-Agent, pull requests merged in 2025-05, with the labels that each got.

#57 Fixes #55 : Display UI for txns
  src/app/dashboard/page.tsx
  src/lib/sampleData.ts
Labels: enhancement

#59 Fixes #58 : Show connected wallet address below NEAR balance in Navbar
  src/app/dashboard/page.tsx
Labels: enhancement

#66 Fixes #61 : Add QR code on dashboard for BTC address
  package.json
  pnpm-lock.yaml
  src/app/dashboard/page.tsx
  src/components/ui/dialog.tsx
Labels: enhancement

#77 Fixes #75 : Code Cleanup: General Refactoring and Improvements
  src/app/api/tools/create-btc-mpc-txn/route.ts
  src/app/api/tools/get-btc-balance/route.ts
  src/app/api/tools/get-btc-txns/route.ts
  src/app/api/tools/get-user/route.ts
  src/app/api/tools/send-btc-txn/route.ts
  src/app/dashboard/page.tsx
  src/components/dashboard/TransactionHistory.tsx
Labels: enhancement

#82 Fixes #80 : pull request template
  pull_request_template.md
Labels: documentation

#87 Fixes #86 : Add banner to Readme
  README.md
  public/assets/banner.png
Labels: documentation

#90 Fixes #88 : Update Readme content with latest changes
  README.md
Labels: documentation

#91 Fixes #89 : Fix the Issue template
  issue_template.md
Labels: bug
